export const APP_UPDATE_MENU = "APP_UPDATE_MENU"
export const APP_UPDATE_POWER = "APP_UPDATE_POWER"
export const APP_UPDATE_USER = "APP_UPDATE_USER"
export const APP_UPDATE_MENU_SMALL = "APP_UPDATE_MENU_SMALL"